import React from 'react';
import type { AnalysisResult } from '../types';
import { NewspaperIcon, ListIcon, BalanceIcon, UsersIcon, GlobeIcon, ThumbsUpIcon, ThumbsDownIcon } from './IconComponents';

interface AnalysisDisplayProps {
  result: AnalysisResult;
}

interface SectionProps {
  title: string;
  icon: React.ReactNode;
  children: React.ReactNode;
}

const AnalysisSection: React.FC<SectionProps> = ({ title, icon, children }) => (
  <div className="bg-white dark:bg-slate-800/50 rounded-lg shadow-md p-6">
    <div className="flex items-center mb-4">
      <div className="w-8 h-8 text-blue-500">{icon}</div>
      <h3 className="ml-3 text-xl font-bold text-slate-800 dark:text-slate-100">{title}</h3>
    </div>
    <div className="text-slate-600 dark:text-slate-300 space-y-2">{children}</div>
  </div>
);

const AnalysisDisplay: React.FC<AnalysisDisplayProps> = ({ result }) => {
  const getToneColor = (tone: 'Positive' | 'Negative' | 'Neutral' | 'Mixed') => {
    switch (tone) {
      case 'Positive': return 'text-green-500';
      case 'Negative': return 'text-red-500';
      case 'Mixed': return 'text-purple-500';
      case 'Neutral': return 'text-yellow-500';
    }
  };

  return (
    <div className="space-y-6">
      <AnalysisSection title="Headline" icon={<NewspaperIcon />}>
        <p className="text-2xl font-semibold text-slate-900 dark:text-white">{result.headline}</p>
      </AnalysisSection>

      <AnalysisSection title="Summary" icon={<ListIcon />}>
        <p className="leading-relaxed">{result.summary}</p>
      </AnalysisSection>

      <div className="grid md:grid-cols-2 gap-6">
        <AnalysisSection title="Pros" icon={<ThumbsUpIcon />}>
          <ul className="list-disc list-inside space-y-2">
            {result.pros.map((pro, index) => <li key={index}>{pro}</li>)}
          </ul>
        </AnalysisSection>

        <AnalysisSection title="Cons" icon={<ThumbsDownIcon />}>
          <ul className="list-disc list-inside space-y-2">
            {result.cons.map((con, index) => <li key={index}>{con}</li>)}
          </ul>
        </AnalysisSection>
      </div>

      <div className="grid md:grid-cols-2 gap-6">
        <AnalysisSection title="Tone Analysis" icon={<BalanceIcon />}>
            <p><strong className={`font-semibold ${getToneColor(result.toneAnalysis.tone)}`}>{result.toneAnalysis.tone}</strong> – {result.toneAnalysis.reason}</p>
        </AnalysisSection>

        <AnalysisSection title="Key Stakeholders" icon={<UsersIcon />}>
            <div className="flex flex-wrap gap-2">
                {result.keyStakeholders.map((stakeholder, index) => (
                    <span key={index} className="bg-blue-100 text-blue-800 text-sm font-medium px-2.5 py-0.5 rounded-full dark:bg-blue-900 dark:text-blue-300">
                        {stakeholder}
                    </span>
                ))}
            </div>
        </AnalysisSection>
      </div>

      <AnalysisSection title="Citizen Impact Summary" icon={<GlobeIcon />}>
        <p className="font-medium italic">{result.citizenImpactSummary}</p>
      </AnalysisSection>
      
      <p className="text-center text-sm text-slate-500 dark:text-slate-400 pt-4">— Generated by CivicLens AI</p>
    </div>
  );
};

export default AnalysisDisplay;
